story5/urls.py
from django.urls import path,include
from django.shortcuts import render
from django.conf.urls import url
from . import views

app_name='story5'
urlpatterns=[
	path('jadwal/',views.createJadwal,name='jadwal'),
	url(r'^delete/(?P<table_id>[0-9]+)/$',views.deleteJadwal, name='deleteJadwal'),

]

story6/urls.py
from django.urls import path, include
from django.shortcuts import render
from django.conf.urls import url
from .views import *

app_name = 'story6'
urlpatterns = [
    path('kegiatan/', landing, name='landing'),
    path('kegiatan/hasil/', listAcara, name='listAcara'),
    path('kegiatan/hasil/register/<int:index>/', register, name='register'),
    path('kegiatan/hasil/<int:index>/', hapus_nama, name='hapus_nama'),

]

storyPPW/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('profile/', views.profile),
    path('project/', views.project),
    path('story1/', views.story1),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('story9/', include('story9.urls')),

]

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    Nama_Kegiatan = models.CharField(max_length=120)


class Peserta(models.Model):
    Nama_Peserta = models.CharField(max_length=120)
    Ikut_Kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE,  null=True, blank=True)

story6/forms.py
from django import forms

from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = [
            'Nama_Kegiatan',
        ]

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'Nama_Peserta',
        ]

story6/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm

# Create your views here.


def landing(request):
    if request.method == 'POST':
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/kegiatan/')
    else:
        form = KegiatanForm()
    return render(request, 'landing.html', {'form': form})


def listAcara(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()

    return render(request, 'hasilKegiatan.html', {'kegiatan': kegiatan, 'peserta': peserta})


def register(request, index):
    if request.method == 'POST':
        form = PesertaForm(request.POST)
        if form.is_valid():
            pesertaBaru = Peserta(Ikut_Kegiatan=Kegiatan.objects.get(
                id=index), Nama_Peserta=form.data['Nama_Peserta'])
            pesertaBaru.save()
            return redirect('../../')
    else:
        form = PesertaForm()
    return render(request, 'tambahPeserta.html', {'form': form})


def hapus_nama(request, index):
    obj_temp = get_object_or_404(Peserta, id=index)  # mengambilnamaobject

    if request.method == 'POST':
        obj_temp.delete()
        return redirect('../')

    context = {
        'object_hapus': obj_temp
    }

    return render(request, "hapusNama.html", context)

story6/templates/hapusNama.html
{% extends 'includes/navbar.html' %}
{% load static %}

{% block meta %}
<title>Welcome!</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% endblock meta %}

{% block content %}
    <div class="container" style="margin-top: 2rem;">
        <h4>Are you sure want to delete {{ object_hapus.Nama_Peserta }} ?</h4>
    </div>

    <div class="container" style="margin-top: 2rem;">
        <form action="." method="POST">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Hapus" style="margin-right: 1rem;"/> 
            <a href="../" class="btn btn-primary">Cancel</a>
        </form>
    </div>

{% endblock content %}

story6/templates/hasilKegiatan.html
{% extends 'includes/navbar.html' %}
{% load static %}

{% block meta %}
<title>Welcome!</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% endblock meta %}

{% block content %}
    <div class="container" style="margin-top: 10vh; margin-bottom: 20vh;">
        <h2 style="color: black;">Daftar Kegiatan dan Peserta</h2>
        <a type="button" class="btn btn-success" href="../../" style="margin-top: 2rem;">Home</a>
        <a type="button" class="btn btn-primary" href="../" style="margin-top: 2rem;">Tambah Kegiatan</a>
    </div>

    {% for x in kegiatan %}
        <div class="container">
            <table class="table table-bordered">
                <tr>
                    <td class='table-secondary'> <b> {{ x.Nama_Kegiatan }} </b> </td>
                </tr>
                <tr>
                    {% for y in peserta %}
                        {% if y.Ikut_Kegiatan == x %}
                        <tr>
                            <td> - {{ y.Nama_Peserta }} <a type="button" class="btn btn-outline-danger" href="{% url 'story6:hapus_nama' y.id %}">Hapus</a> </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tr>
            </table>
        </div>

        <div class="container text-center" style="margin-bottom: 3rem;"> 
            <a href="register/{{ x.id }}" class="text-white btn btn-primary mx-auto my-2 click">
                Register {{ x.Nama_Kegiatan }}
            </a>
        </div>
    {% endfor %}

    <div class="container" style="margin-bottom: 10rem;">
    </div>

{% endblock content %}

story6/templates/landing.html
{% extends 'includes/navbar.html' %}
{% load static %}

{% block meta %}
<title>Welcome!</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% endblock meta %}

{% block content %}
    <div class="container" style="margin-top: 30vh;">
        <h2 style="color: black;">Tambah Kegiatan</h2>
    </div>

    <div class="container justify-content-center" style="margin-top: 20vh; margin-bottom: 10vh;">
        <form method="POST"> 
            {% csrf_token %}
            {{ form }}
            <h5 style="margin-top: 2rem;">* = Wajib Diisi</h5>
            <input style="margin-top: 2rem;" class="btn btn-primary" type="submit" value="Save" />
            <a type="button" class="btn btn-primary" href="hasil/" style="margin-top: 2rem; margin-left: 2rem;">Lihat Kegiatan dan Peserta</a>
            <a type="button" class="btn btn-success" href="../" style="margin-top: 2rem; margin-left: 2rem;">Home</a>
        </form>
    </div>

    <div class="container" style="margin-bottom: 10rem;">
    </div>

{% endblock content %}

story6/templates/tambahPeserta.html
{% extends 'includes/navbar.html' %}
{% load static %}

{% block meta %}
<title>Welcome!</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% endblock meta %}

{% block content %}
    <div class="container justify-content-center" style="margin-top: 20vh; margin-bottom: 10vh;">
        <form method="POST"> {% csrf_token %}
            {{ form }}
            <h5 style="margin-top: 2rem;">* = Wajib Diisi</h5>
            <input style="margin-top: 2rem;" class="btn btn-primary" type="submit" value="Save" />
            <a type="button" class="btn btn-danger" href="../../" style="margin-top: 2rem; margin-left: 2rem;">Back</a>
        </form>
    </div>

    <div class="container" style="margin-bottom: 10rem;">
    </div>

{% endblock content %}