story5/urls.py
from django.urls import path,include
from django.shortcuts import render
from django.conf.urls import url
from . import views

app_name='story5'
urlpatterns=[
	path('jadwal/',views.createJadwal,name='jadwal'),
	url(r'^delete/(?P<table_id>[0-9]+)/$',views.deleteJadwal, name='deleteJadwal'),

]

storyPPW/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('profile/', views.profile),
    path('project/', views.project),
    path('story1/', views.story1),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('story9/', include('story9.urls')),

]

story5/models.py
from django.db import models

class modelMatkul(models.Model):
	mataKuliah = models.TextField(max_length=300)
	dosenPengajar = models.TextField(max_length=300)
	jumlahSKS = models.TextField(max_length=300)
	deskripsi = models.TextField(max_length=300)
	semester = models.TextField(max_length=300)

story5/forms.py
from django import forms
from . import models


class formMatkul(forms.Form):
    mataKuliah = forms.CharField(max_length=300, required=True)
    dosenPengajar = forms.CharField(max_length=300, required=True)
    jumlahSKS = forms.CharField(max_length=300, required=True)
    deskripsi = forms.CharField(max_length=300, required=True)
    semester = forms.CharField(max_length=300, required=True)

story5/views.py
from django.shortcuts import render, redirect
from .forms import formMatkul
from .models import modelMatkul


def landing(request):
    return render(request, 'landing.html')


def createJadwal(request):
    matkul = modelMatkul.objects.all()
    createMatkul = formMatkul(request.POST or None)  # POST vs GET
    context = {
        'matkul': matkul,
        'createMatkul': createMatkul
    }

    if request.method == 'POST':
        if createMatkul.is_valid():
            matkul.create(
                mataKuliah=createMatkul.cleaned_data.get('mataKuliah'),
                dosenPengajar=createMatkul.cleaned_data.get('dosenPengajar'),
                jumlahSKS=createMatkul.cleaned_data.get('jumlahSKS'),
                deskripsi=createMatkul.cleaned_data.get('deskripsi'),
                semester=createMatkul.cleaned_data.get('semester'),
            )
    return render(request, 'jadwal.html', context)


def deleteJadwal(request, table_id=None):
    matkul = modelMatkul.objects.get(id=table_id)
    matkul.delete()
    return redirect('/jadwal/')
# Create your views here.

story5/templates/jadwal.html
{% extends 'includes/navbar.html' %}
{% load static %}

{% block meta %}
<title>Welcome!</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% endblock meta %}

{% block content %}
<header>
    <h1>
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>  
        <center>Jadwal Kuliah</center>
    </h1>
</header>

<form method="post">
    {% csrf_token %}
    {{ createMatkul.as_table }} <br>
    <input type="submit" value="Submit">
</form>

<table class="table table-dark table-striped">
<thead>
    <tr>
        <th scope="col">Mata Kuliah</th>
        <th scope="col">Dosen</th>
        <th scope="col">Jumlah SKS</th>
        <th scope="col">Deskripsi</th>
        <th scope="col">Semester</th>
    </tr>
</thead>
<tbody>
    {% for mat in matkul %}
        <tr>
            <th scope="row">{{mat.mataKuliah}}</th>
            <th>{{mat.dosenPengajar}}</th>
            <td>{{mat.jumlahSKS}}</td>
            <td>{{mat.deskripsi}}</td>
            <td>{{mat.semester}}</td>
            <td><a href="{% url 'story5:deleteJadwal' table_id=mat.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
</tbody>
</table>
{% endblock content %}